// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsx9eaLOGdgrq_R2HuEjoo0F2A6ZOkYdY',
    appId: '1:99409921345:web:52808863da806611564dc0',
    messagingSenderId: '99409921345',
    projectId: 'avsec--portal-ver100',
    authDomain: 'avsec--portal-ver100.firebaseapp.com',
    databaseURL: 'https://avsec--portal-ver100.firebaseio.com',
    storageBucket: 'avsec--portal-ver100.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVVjGzySXn5cU5Kj8NEiQFsA1N7bIBz4',
    appId: '1:99409921345:android:247ec017c67bbb2f564dc0',
    messagingSenderId: '99409921345',
    projectId: 'avsec--portal-ver100',
    databaseURL: 'https://avsec--portal-ver100.firebaseio.com',
    storageBucket: 'avsec--portal-ver100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Mp3R0lIsBtRePqMuKAhM8ge25DO5I3g',
    appId: '1:99409921345:ios:2e468d7ef3954aca564dc0',
    messagingSenderId: '99409921345',
    projectId: 'avsec--portal-ver100',
    databaseURL: 'https://avsec--portal-ver100.firebaseio.com',
    storageBucket: 'avsec--portal-ver100.appspot.com',
    androidClientId: '99409921345-rnqvhf6dfpcaovrrj95p0uv08kv2nuld.apps.googleusercontent.com',
    iosClientId: '99409921345-ng0trkgh3i1u1g42lhn35l0k3ml5gmg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.greentie',
  );
}
